# Generated by Django 3.0.5 on 2020-04-19 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='available_selling_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='conclusion_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='evaluation_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='evaluation_plus_minus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='revenue_rate',
            field=models.IntegerField(null=True),
        ),
    ]
